services:
  rhysserverv2:
    build: ./
    container_name: RhysServerV2_APP
    ports:
      - 8080:8080
    networks:
      - default
      # - proxy
    restart: unless-stopped
    # labels:
    #   # Traefik (uncomment if using traefik reverse proxy)
    #   - traefik.enable=true
    #   - traefik.http.routers.rhysserverv2.entrypoints=websecure
    #   - traefik.http.routers.rhysserverv2.rule=Host(`rhysbot.com`)
    #   - traefik.http.services.rhysserverv2.loadbalancer.server.port=8080

  db:
    image: mongo
    container_name: RhysServerV2_DB
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: rhysserverv2
      MONGO_INITDB_ROOT_PASSWORD: example # Replace with an actual password
# networks:
#   proxy:
#     external: true
